### ISSUE TITLE
Does this code only implement the forward propagation shift operation?

### ISSUE THREAD

**Issue by mengjingyouling** [mostafaelhoushi/DeepShift#14]
Great job!

There are some questions. Does this code only implement the forward propagation shift operation? The back-propagation shift operation code is not found? Can you explain where the back propagation code is?

thank you!
@mostafaelhoushi

**Comment by mengjingyouling** [comment]
Backward is implemented in the conv2dshiftqfunction function, but we don't see where to call it?
 Is there something wrong with us? Thank you!

**Comment by mengjingyouling** [comment]
@mostafaelhoushi

**Comment by mengjingyouling** [comment]
@chenzi26 @yehenrytian

**Comment by mostafaelhoushi** [comment]
I apologize for the delay.
I would like to clarify that PyTorch automatically invokes the backward pass. 

You can see this documentation for more details:
https://pytorch.org/docs/stable/notes/extending.html#example
Basically, in PyTorch, you create a class that inherits from the `torch.nn.Function` class, and create a `forward()` function and a `backward()` function. 

This way, the forward pass is automatically called by PyTorch when you apply that class, and the backward pass will be automatically called by PyTorch as part of its autograd.

Please don't hesitate to tell me if you would like more details or clarification.

**Comment by mengjingyouling** [comment]
Thank you very much.

**Comment by mostafaelhoushi** [comment]
Please note, that we only use that handwritten backward pass if `use_kernel` is True:
https://github.com/mostafaelhoushi/DeepShift/blob/master/pytorch/deepshift/modules_q.py#L124-L125

Please feel free to re-open the Issue.

**Comment by mengjingyouling** [comment]
Thank you very much！



发自我的iPhone


------------------ Original ------------------
From: Mostafa Elhoushi ***@***.***&gt;
Date: Mon,Mar 28,2022 9:59 PM
To: mostafaelhoushi/DeepShift ***@***.***&gt;
Cc: mengjingyouling ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [mostafaelhoushi/DeepShift] Does this code only implement the forward propagation shift operation? (Issue #14)





 
Please note, that we only use that handwritten backward pass if use_kernel is True:
 https://github.com/mostafaelhoushi/DeepShift/blob/master/pytorch/deepshift/modules_q.py#L124-L125
 
Please feel free to re-open the Issue.
