### ISSUE TITLE
test mAP

### ISSUE THREAD

**Issue by mengjingyouling** [mostafaelhoushi/DeepShift#19]
The minist.py code implements the training process of the Deepshift method. As it is a complete process, the model is trained and then tested. The test model is generated using model. eval (). After training, save the model weight file (. pth).This training process can achieve high accuracy(train_log.csv).

However, we found that loading the generated weight file(weights.pth) for inference(test fuction) will reduce the accuracy.

Do you have any suggestions?

Thanks!

**Comment by mengjingyouling** [comment]
@mostafaelhoushi

**Comment by mengjingyouling** [comment]
It should be the weight obtained from training. Before inference, it needs to be quantized by Deepshift method.

**Comment by mengjingyouling** [comment]
Thanks

**Comment by mostafaelhoushi** [comment]
Sorry for the delay. Were you able to solve the problem?
