### ISSUE TITLE
Advantages compared to int8

### ISSUE THREAD

**Issue by mengjingyouling** [mostafaelhoushi/DeepShift#22]
HI @mostafaelhoushi ：

Theoretically, int8 can be 3-4 times faster than FP32.
But in the current paper, there is almost no comparison with int8, because of any disadvantages of int8?

For example, the APOT paper reported that its paper speed is twice that of FP32, and it should be slower than int8.

https://github.com/yhhhli/APoT_Quantization

Looking forward to your reply, thank you very much！

Best wishes
@mostafaelhoushi

**Comment by mostafaelhoushi** [comment]
Hi @mengjingyouling 
Sorry for the delay in my response.

You are right, it would have been better if I added an INT8 comparison. 

I would like to mention that theoretically 3-bit or 4-bit quantization (whether DeepShift or APoT) should be faster than INT8.
However, practically, INT8 kernels are well supported in CPU and GPU by PyTorch, NVIDIA, and Intel over the past years so you will find them faster than our DeepShift 3-bit or 4-bit kernels. One of the goals of the paper is to encourage hardware companies and software libraries to invest into implementing and optimizing those 3-bit or 4-bit quantization types.

**Comment by mostafaelhoushi** [comment]
I recommend looking at Riptide: https://octoml.ai/blog/riptide-fast-full-binarization-in-tvm/
I think they have efficient implementation of 1-bit, 2-bit and 4-bit quantization (although not using bitwise shift) that should be faster than INT8.

**Comment by mengjingyouling** [comment]
I get it, thank you.
