### ISSUE TITLE
does wx+b or wx not need to be quantified?

### ISSUE THREAD

**Issue by mengjingyouling** [mostafaelhoushi/DeepShift#23]
hi @mostafaelhoushi 

In your excellent work Deepshift, where input x and activation are quantified, does wx+b or wx not need to be quantified? If they don't quantify it, they should be occupying 64 bits of memory, right?Does this affect model acceleration？

best wishes

thank you！

**Comment by mostafaelhoushi** [comment]
Hello @mengjingyouling 
Sorry for the delay in my response.
This is a very good question. I didn't quantize the output of convolution or linear layer and I assume that they are 32-bit.
Many papers do that: quantize input and make the result in higher precision. My understanding this will keep the accuracy higher while not affecting speed much.

However, quantizing the result could lead to lower memory consumption and hence in training allow a larger batch size and hence speedup training.
So there are other papers thatdo quantize output as well.
For example, the 2016 quantization paper of Bengio does quantize the output (see Algorithm 1 in https://arxiv.org/pdf/1609.07061.pdf )
Also, another paper, Riptide, does quantize output: https://octoml.ai/blog/riptide-fast-full-binarization-in-tvm/

**Comment by mengjingyouling** [comment]
I get it,thank you.
