### ISSUE TITLE
We used shift type of PS to train resnet-18 from source but it did not converge.

### ISSUE THREAD

**Issue by PoonKinWang** [mostafaelhoushi/DeepShift#8]
The training strictly followed README and converged on MNIST. 
However, we used shift type of PS to train resnet-18 but it did not converge, and we got top-1 acc of 5.13% on val dataset after 90 epochs training. We ensure no problem in dataset.
Could you provide some guides for this?

**Comment by mostafaelhoushi** [comment]
Hi @PoonKinWang . Thanks for trying the code, and I am sorry that you got that mistake.

For training using DeepShift we need to have a learning rate of 0.01, and for DeepShift-PS in particular, we need the RAdam optimizer. So I want to ask, did you inlcude the options `--lr 0.01 --optimizer radam` when training?

Below, is the training log I got.  The first epoch reached a Top-1/Top5 accuracy of about 15%/35%. If you don't get that accuracy after the first epoch, please inform me and we can work on it together.
```
epoch,train_loss,train_top1_acc,train_top5_acc,train_time,test_loss,test_top1_acc,test_top5_acc,test_time,cumulative_time
0,5.920666382148783,6.1568866,16.037098,1.5971847723294923,4.398006581726074,15.398,35.29,0.9922469039352573,8189.1828327178955
1,4.139687943162871,22.347515,44.28197,1.5962595488998916,3.561975800476074,26.778,51.022,0.9874977408623209,16375.367124557495
2,3.496611715681115,31.773218,55.976204,1.5966112650834121,3.0676476147460936,34.322,59.983997,0.9875998253725013,24563.655780553818
3,3.181493104853973,36.922195,61.513054,1.5958974191358872,2.6901432064819337,40.975998,66.327995,1.000882905356738,32750.907382249832
4,2.9893891139961104,40.22286,64.85233,1.5958547572632293,2.4960606536865235,44.149998,70.256,0.9859313003870905,40934.842067956924
5,2.855411642023814,42.635895,67.12312,1.595777431091705,2.3679007550048827,46.539997,72.02,0.9870308345677902,49118.85495853424
6,2.7588976041040723,44.359478,68.727036,1.5958274369711405,2.3452695655822753,46.733997,72.602,0.9963134356907436,57304.856921195984
7,2.6823799746409613,45.71012,69.96085,1.5956042361664367,2.2146408057403564,49.538,74.745995,0.98568850269123,65487.5652718544
8,2.6195723851242914,46.87648,70.98683,1.5962557361557053,2.233407511367798,49.288,74.453995,0.9913649291408305,73674.77141070366
9,2.5676660919364904,47.819683,71.83988,1.5956154771379896,2.1801577334594726,50.126,75.551994,0.9892421072843124,81857.33332705498
10,2.527640398007509,48.536217,72.399864,1.5961046280798974,2.1153628385925294,51.614,76.346,0.9934437335753927,90044.17346692085
11,2.487345225244158,49.24315,73.085915,1.596046461425461,2.276991346206665,48.472,73.862,0.9852774629787523,98229.35267496109
12,2.4512656732718736,49.954376,73.65048,1.5961493457352127,2.0463910842895507,52.638,77.42,0.9867703488894871,106414.26143574715
13,2.4233181591947632,50.488735,74.060974,1.5959391949774622,2.070989427719116,52.308,77.166,0.9976263253056273,114601.08451962471
14,2.3996123787276624,50.88915,74.47119,1.5960020847492047,2.008532763519287,53.663998,78.285995,0.9843792927508451,122784.72535777092
15,2.380143429253888,51.28894,74.77497,1.5957188851111657,2.0758800340270995,52.364,76.89,1.001999659197671,130971.324041605
16,2.3573767779162296,51.696537,75.103485,1.5958164962974342,1.947855902709961,54.798,78.925995,0.9837841415891841,139153.7425673008
17,2.3416682757877467,52.040756,75.36236,1.59592404760919,2.110160852355957,51.696,76.486,0.9859706637810688,147338.24855613708
18,2.325993285173931,52.33666,75.62825,1.595847565644271,1.9398536853790282,54.868,79.406,0.9871408562270962,155521.62215590477
19,2.3053487877603445,52.715687,75.91569,1.5958235964074836,2.033626317062378,53.194,77.756,0.9854765631714646,163705.64277935028
20,2.2951987717473656,52.934258,76.14081,1.5961564004004418,2.0174264595031737,53.578,78.016,0.9857319848878043,171890.16023659706
21,2.2830902985357957,53.148045,76.29927,1.5956188653494332,1.9447173029327394,54.851997,79.322,1.0047890045204941,180076.1049809456
22,2.2714772863316868,53.40256,76.42113,1.5957883129824888,1.8318058653259277,57.132,80.638,0.9861706677748232,188258.87262105942
23,2.2593132997920855,53.62665,76.67092,1.5956588246843793,1.9658969410705567,54.524,78.89,0.9904728373702691,196442.8909187317
24,2.250530799809408,53.77493,76.84797,1.5957139512042067,1.9173802843475343,55.3,79.588,0.9893482157162258,204626.01322984695
25,2.2407947504575696,53.946445,76.982315,1.5962452570279757,1.8616962074279786,56.606,80.74,0.9997629669247842,212813.77724695206
26,2.2306904623407697,54.209137,77.14951,1.5963867721024092,1.9720584384155273,54.516,78.458,0.9915777992229072,221001.74967336655
27,2.221768917322732,54.40486,77.2722,1.5958913433920967,1.9686556315612793,54.648,79.096,0.9881973534214253,229185.43120741844
28,2.2150107210260086,54.525932,77.36905,1.5967754228727205,1.8528707615661621,56.747997,80.409996,0.992271926938271,237374.46097540855
29,2.2066548508758945,54.69578,77.524345,1.5958593203233076,2.2555685179138183,49.593998,73.948,0.9901400500414322,245558.46975564957
30,1.9802628268808606,59.33563,80.65725,1.5959975750415356,1.5932874185943604,62.12,84.122,0.9859152460584835,253742.25171089172
31,1.9331703963729252,60.22503,81.26571,1.5956786994095686,1.6184215144348144,61.848,83.773994,0.9855728818445789,261925.73238182068
32,1.9083920737991746,60.59745,81.58557,1.59611371828245,1.5965042967224121,62.247997,84.203995,0.9871191199944944,270110.3737962246
33,1.8944876242719875,60.832413,81.74477,1.5958668933643565,1.651139925918579,61.005997,83.362,0.9924816744668143,278295.7607035637
34,1.8846505443244157,60.991924,81.82078,1.5964732423528925,1.5461576490020752,63.26,84.897995,0.9955884656127618,286483.9442577362
35,1.8718596158074623,61.15487,81.98107,1.595762417009184,1.5695059725952147,62.781998,84.528,0.9857814652579171,294667.5588181019
36,1.8636270928889629,61.30117,82.06729,1.5961411123628264,1.605586051635742,62.03,83.981995,0.9914867464376955,302853.23594594
37,1.8542905752088539,61.426407,82.18418,1.5961942871848305,1.5440804751586914,63.434,84.832,0.9881194902926075,311038.57649207115
38,1.8478160335519382,61.552532,82.24143,1.596073254814872,1.5446234474182128,63.5,84.9,0.9868558961517957,319222.8898997307
39,1.8425396732679795,61.5883,82.31674,1.5962434042702902,1.5962256549072265,62.208,84.093994,1.0016732544315106,327412.0997085571
40,1.8344493971267077,61.69503,82.35185,1.5965319112345175,1.5905594931030274,62.244,84.105995,0.9907003543814834,335599.60433745384
41,1.82985852263482,61.781673,82.39964,1.5956612455499517,1.5561007110595704,63.137997,84.729996,0.9883214502918477,343782.62270975113
42,1.823927956299255,61.882168,82.48423,1.59669036517491,1.6529216536712648,60.898,83.364,0.9874654059507408,351970.313993454
43,1.819863584242137,61.93021,82.47523,1.5956951232818695,1.549367647628784,63.283997,84.878,0.9901057092510924,360153.4763972759
44,1.814927366213781,61.9878,82.53972,1.5959356544734715,1.5739458898162841,62.774,84.574,0.9888240330073298,368337.68942284584
45,1.8085399194012344,62.04557,82.61719,1.595841582838472,1.5455463536071776,63.219997,84.976,1.0035860939901702,376524.33398246765
46,1.8067773948777954,62.070908,82.61325,1.5963170266889788,1.5293461030578612,63.584,85.102,0.9884823901312692,384711.3088710308
47,1.8009222509859193,62.16584,82.693634,1.596596061504566,1.580091997680664,62.651997,84.5,0.9874566233887965,392900.01472234726
48,1.7988997630743937,62.15473,82.70844,1.5961038592335703,1.5740102394104003,62.778,84.481995,0.9903077252057134,401085.1830379963
49,1.7928610277756407,62.23562,82.80091,1.5964206661735023,1.5635312223815918,63.205997,84.61,0.9904849675236916,409272.19001841545
50,1.7895275318851496,62.328835,82.814255,1.5965852663114473,1.5478022785949708,63.357998,84.937996,0.9918795702408771,417460.24165296555
51,1.7856588239815296,62.371815,82.87439,1.5968933715210571,1.5645631693267823,63.093998,84.565994,0.9946745208331517,425650.7308907509
52,1.7832213586705161,62.363964,82.868996,1.5958284252292507,1.7047852919769286,60.148,82.486,0.9917372720582145,433834.90649080276
53,1.7773567144855016,62.493248,82.94041,1.596218554528205,1.637491718597412,61.732,83.7,0.995179291890592,442021.7151954174
54,1.7758111060115331,62.478294,82.9551,1.5961806241568033,1.5464856290435791,63.278,85.021996,1.0004514820721684,450209.45535469055
55,1.7720111928349258,62.527977,82.96277,1.5965961740209864,1.5264092684173585,63.989998,85.29,1.0025294666387596,458399.58895516396
56,1.7685069872539325,62.57615,83.00268,1.5960595307173906,1.571856334915161,62.904,84.464,0.9913304107529777,466585.9665915966
57,1.7676819896856402,62.58264,83.00579,1.5965751370230874,1.519931905441284,64.072,85.214,0.9907919995638789,474773.672283411
58,1.7633828021756386,62.651028,83.05242,1.5966254869779268,1.5296032257843017,63.649998,85.182,1.0069580552529316,482964.8543624878
59,1.762230389919614,62.642574,83.03271,1.5966327063210837,1.518884241104126,64.066,85.411995,0.9922091547323733,491153.0843036175
60,1.7105733353304722,63.817917,83.7703,1.5964635649403849,1.4506889158630372,65.521996,86.222,0.9931325693519748,499341.74523472786
61,1.7047658753585624,63.9427,83.81546,1.5963242304551375,1.4501313687896729,65.46,86.214,0.9904440166998882,507529.5082395077
62,1.7029816968330318,63.94094,83.83007,1.5960700542895825,1.443698380355835,65.626,86.332,0.999058375553209,515716.308709383
63,1.7006617817973932,63.97508,83.89523,1.5957233719535164,1.4619855323791504,65.278,86.145996,1.0029854373056062,523903.1655244827
64,1.7011770515706328,63.989563,83.84739,1.5961855434394858,1.502848649597168,64.369995,85.502,0.9881741732967143,532088.5214724541
65,1.701400187242035,63.9714,83.86066,1.596170193093878,1.4573842282104492,65.383995,86.131996,0.9854576210586392,540273.5961740017
66,1.7005492970140317,64.00479,83.87039,1.5958774974891594,1.4698494776153563,64.906,86.058,0.9978820207167645,548459.2700073719
67,1.7005864492513805,63.93207,83.84804,1.6865760898971176,1.5263512521362306,63.904,85.259995,0.9936201913016183,557097.973174572
68,1.6998434647688,63.985138,83.89892,1.6153854569712363,1.45822073387146,65.27,86.133995,1.003535471400436,565382.2523198128
69,1.7003657271536816,63.96872,83.85166,1.5963282653263637,1.481093205871582,64.79,85.764,0.9857255354219553,573567.9607219696
70,1.7003885606694944,63.928326,83.8484,1.5965747860404518,1.505466459503174,64.074,85.436,1.0053336328389693,581758.9002225399
71,1.7015631769043245,63.9033,83.847626,1.595787447625464,1.5278383959960937,63.808,85.173996,0.9900182327445672,589942.877510786
72,1.697550265988844,63.966656,83.911835,1.5956486492366582,1.4644882872772216,65.159996,85.964,0.9959038544674309,598127.0380961895
73,1.700625746160773,63.914783,83.86695,1.5958980614131504,1.454816374053955,65.32,86.285995,1.0093149773928585,606314.997260809
74,1.7021390240779841,63.886078,83.840225,1.5969835279466627,1.5105508098602294,64.284,85.423996,0.9932024612718698,614505.14006567
75,1.7023710900860165,63.92633,83.85161,1.5959557027845355,1.4780098268127442,64.902,85.81,0.9847620798616993,622688.6121582985
76,1.6997852312980404,63.918262,83.88021,1.595850592059689,1.4782607787322999,64.902,85.818,1.0041363190631478,630875.3205928802
77,1.6992308229059185,64.01019,83.882286,1.596750420742816,1.4733256831359862,65.096,86.012,0.9946229615989997,639064.9259705544
78,1.7002029050045773,63.91405,83.83968,1.5969988569989428,1.5069794171905517,64.434,85.444,0.9870273081623778,647253.9411637783
79,1.7007536462828836,63.914997,83.83266,1.5961824518102747,1.5035199520874023,64.416,85.486,1.0089637515496235,655443.2620053291
80,1.6994928737155506,63.906315,83.87964,1.5960338774975482,1.464080915145874,65.254,86.076,1.0079378327544855,663631.658523798
81,1.6979317820993614,63.940815,83.897095,1.5959332480416313,1.4795377980804443,64.708,85.796,0.9878113135999563,671816.1759848595
82,1.7000740477349692,63.89565,83.85333,1.596167873312067,1.4589048153686524,65.318,86.06,0.9980773633840133,680003.7541818619
83,1.6971413652078178,64.00678,83.871376,1.5966329814670803,1.5329412049865723,63.573997,84.992,0.98514666727611,688190.5998697281
84,1.6984173363687638,63.93113,83.899086,1.5961399444214233,1.4762832211303711,64.944,85.974,0.9895148849000737,696375.9652450085
85,1.6983990221635619,63.95159,83.88598,1.5962878441596247,1.4815700963592529,64.892,85.908,0.9939260884207122,704562.8491721153
86,1.69557271798417,64.01502,83.90125,1.5967913878666653,1.516679326171875,64.236,85.341995,1.0039535797372157,712754.3144705296
87,1.6994829859870804,63.966194,83.8501,1.5966947032974197,1.4664484536743163,64.972,86.077995,1.0077411155311429,720945.9214494228
88,1.6970900383199357,63.905487,83.8847,1.5965777459559025,1.5180966523742676,63.934,85.368,1.0067482432540582,729136.6450090408
89,1.6975512266464625,63.927776,83.87759,1.5965711550755457,1.465786263961792,65.28,85.979996,0.9965298406931818,737325.5609092712
```

**Comment by PoonKinWang** [comment]
> Hi @PoonKinWang . Thanks for trying the code, and I am sorry that you got that mistake.
> 
> For training using DeepShift we need to have a learning rate of 0.01, and for DeepShift-PS in particular, we need the RAdam optimizer. So I want to ask, did you inlcude the options `--lr 0.01 --optimizer radam` when training?
> 
> Below, is the training log I got. The first epoch reached a Top-1/Top5 accuracy of about 15%/35%. If you don't get that accuracy after the first epoch, please inform me and we can work on it together.
> 
> ```
> epoch,train_loss,train_top1_acc,train_top5_acc,train_time,test_loss,test_top1_acc,test_top5_acc,test_time,cumulative_time
> 0,5.920666382148783,6.1568866,16.037098,1.5971847723294923,4.398006581726074,15.398,35.29,0.9922469039352573,8189.1828327178955
> 1,4.139687943162871,22.347515,44.28197,1.5962595488998916,3.561975800476074,26.778,51.022,0.9874977408623209,16375.367124557495
> 2,3.496611715681115,31.773218,55.976204,1.5966112650834121,3.0676476147460936,34.322,59.983997,0.9875998253725013,24563.655780553818
> 3,3.181493104853973,36.922195,61.513054,1.5958974191358872,2.6901432064819337,40.975998,66.327995,1.000882905356738,32750.907382249832
> 4,2.9893891139961104,40.22286,64.85233,1.5958547572632293,2.4960606536865235,44.149998,70.256,0.9859313003870905,40934.842067956924
> 5,2.855411642023814,42.635895,67.12312,1.595777431091705,2.3679007550048827,46.539997,72.02,0.9870308345677902,49118.85495853424
> 6,2.7588976041040723,44.359478,68.727036,1.5958274369711405,2.3452695655822753,46.733997,72.602,0.9963134356907436,57304.856921195984
> 7,2.6823799746409613,45.71012,69.96085,1.5956042361664367,2.2146408057403564,49.538,74.745995,0.98568850269123,65487.5652718544
> 8,2.6195723851242914,46.87648,70.98683,1.5962557361557053,2.233407511367798,49.288,74.453995,0.9913649291408305,73674.77141070366
> 9,2.5676660919364904,47.819683,71.83988,1.5956154771379896,2.1801577334594726,50.126,75.551994,0.9892421072843124,81857.33332705498
> 10,2.527640398007509,48.536217,72.399864,1.5961046280798974,2.1153628385925294,51.614,76.346,0.9934437335753927,90044.17346692085
> 11,2.487345225244158,49.24315,73.085915,1.596046461425461,2.276991346206665,48.472,73.862,0.9852774629787523,98229.35267496109
> 12,2.4512656732718736,49.954376,73.65048,1.5961493457352127,2.0463910842895507,52.638,77.42,0.9867703488894871,106414.26143574715
> 13,2.4233181591947632,50.488735,74.060974,1.5959391949774622,2.070989427719116,52.308,77.166,0.9976263253056273,114601.08451962471
> 14,2.3996123787276624,50.88915,74.47119,1.5960020847492047,2.008532763519287,53.663998,78.285995,0.9843792927508451,122784.72535777092
> 15,2.380143429253888,51.28894,74.77497,1.5957188851111657,2.0758800340270995,52.364,76.89,1.001999659197671,130971.324041605
> 16,2.3573767779162296,51.696537,75.103485,1.5958164962974342,1.947855902709961,54.798,78.925995,0.9837841415891841,139153.7425673008
> 17,2.3416682757877467,52.040756,75.36236,1.59592404760919,2.110160852355957,51.696,76.486,0.9859706637810688,147338.24855613708
> 18,2.325993285173931,52.33666,75.62825,1.595847565644271,1.9398536853790282,54.868,79.406,0.9871408562270962,155521.62215590477
> 19,2.3053487877603445,52.715687,75.91569,1.5958235964074836,2.033626317062378,53.194,77.756,0.9854765631714646,163705.64277935028
> 20,2.2951987717473656,52.934258,76.14081,1.5961564004004418,2.0174264595031737,53.578,78.016,0.9857319848878043,171890.16023659706
> 21,2.2830902985357957,53.148045,76.29927,1.5956188653494332,1.9447173029327394,54.851997,79.322,1.0047890045204941,180076.1049809456
> 22,2.2714772863316868,53.40256,76.42113,1.5957883129824888,1.8318058653259277,57.132,80.638,0.9861706677748232,188258.87262105942
> 23,2.2593132997920855,53.62665,76.67092,1.5956588246843793,1.9658969410705567,54.524,78.89,0.9904728373702691,196442.8909187317
> 24,2.250530799809408,53.77493,76.84797,1.5957139512042067,1.9173802843475343,55.3,79.588,0.9893482157162258,204626.01322984695
> 25,2.2407947504575696,53.946445,76.982315,1.5962452570279757,1.8616962074279786,56.606,80.74,0.9997629669247842,212813.77724695206
> 26,2.2306904623407697,54.209137,77.14951,1.5963867721024092,1.9720584384155273,54.516,78.458,0.9915777992229072,221001.74967336655
> 27,2.221768917322732,54.40486,77.2722,1.5958913433920967,1.9686556315612793,54.648,79.096,0.9881973534214253,229185.43120741844
> 28,2.2150107210260086,54.525932,77.36905,1.5967754228727205,1.8528707615661621,56.747997,80.409996,0.992271926938271,237374.46097540855
> 29,2.2066548508758945,54.69578,77.524345,1.5958593203233076,2.2555685179138183,49.593998,73.948,0.9901400500414322,245558.46975564957
> 30,1.9802628268808606,59.33563,80.65725,1.5959975750415356,1.5932874185943604,62.12,84.122,0.9859152460584835,253742.25171089172
> 31,1.9331703963729252,60.22503,81.26571,1.5956786994095686,1.6184215144348144,61.848,83.773994,0.9855728818445789,261925.73238182068
> 32,1.9083920737991746,60.59745,81.58557,1.59611371828245,1.5965042967224121,62.247997,84.203995,0.9871191199944944,270110.3737962246
> 33,1.8944876242719875,60.832413,81.74477,1.5958668933643565,1.651139925918579,61.005997,83.362,0.9924816744668143,278295.7607035637
> 34,1.8846505443244157,60.991924,81.82078,1.5964732423528925,1.5461576490020752,63.26,84.897995,0.9955884656127618,286483.9442577362
> 35,1.8718596158074623,61.15487,81.98107,1.595762417009184,1.5695059725952147,62.781998,84.528,0.9857814652579171,294667.5588181019
> 36,1.8636270928889629,61.30117,82.06729,1.5961411123628264,1.605586051635742,62.03,83.981995,0.9914867464376955,302853.23594594
> 37,1.8542905752088539,61.426407,82.18418,1.5961942871848305,1.5440804751586914,63.434,84.832,0.9881194902926075,311038.57649207115
> 38,1.8478160335519382,61.552532,82.24143,1.596073254814872,1.5446234474182128,63.5,84.9,0.9868558961517957,319222.8898997307
> 39,1.8425396732679795,61.5883,82.31674,1.5962434042702902,1.5962256549072265,62.208,84.093994,1.0016732544315106,327412.0997085571
> 40,1.8344493971267077,61.69503,82.35185,1.5965319112345175,1.5905594931030274,62.244,84.105995,0.9907003543814834,335599.60433745384
> 41,1.82985852263482,61.781673,82.39964,1.5956612455499517,1.5561007110595704,63.137997,84.729996,0.9883214502918477,343782.62270975113
> 42,1.823927956299255,61.882168,82.48423,1.59669036517491,1.6529216536712648,60.898,83.364,0.9874654059507408,351970.313993454
> 43,1.819863584242137,61.93021,82.47523,1.5956951232818695,1.549367647628784,63.283997,84.878,0.9901057092510924,360153.4763972759
> 44,1.814927366213781,61.9878,82.53972,1.5959356544734715,1.5739458898162841,62.774,84.574,0.9888240330073298,368337.68942284584
> 45,1.8085399194012344,62.04557,82.61719,1.595841582838472,1.5455463536071776,63.219997,84.976,1.0035860939901702,376524.33398246765
> 46,1.8067773948777954,62.070908,82.61325,1.5963170266889788,1.5293461030578612,63.584,85.102,0.9884823901312692,384711.3088710308
> 47,1.8009222509859193,62.16584,82.693634,1.596596061504566,1.580091997680664,62.651997,84.5,0.9874566233887965,392900.01472234726
> 48,1.7988997630743937,62.15473,82.70844,1.5961038592335703,1.5740102394104003,62.778,84.481995,0.9903077252057134,401085.1830379963
> 49,1.7928610277756407,62.23562,82.80091,1.5964206661735023,1.5635312223815918,63.205997,84.61,0.9904849675236916,409272.19001841545
> 50,1.7895275318851496,62.328835,82.814255,1.5965852663114473,1.5478022785949708,63.357998,84.937996,0.9918795702408771,417460.24165296555
> 51,1.7856588239815296,62.371815,82.87439,1.5968933715210571,1.5645631693267823,63.093998,84.565994,0.9946745208331517,425650.7308907509
> 52,1.7832213586705161,62.363964,82.868996,1.5958284252292507,1.7047852919769286,60.148,82.486,0.9917372720582145,433834.90649080276
> 53,1.7773567144855016,62.493248,82.94041,1.596218554528205,1.637491718597412,61.732,83.7,0.995179291890592,442021.7151954174
> 54,1.7758111060115331,62.478294,82.9551,1.5961806241568033,1.5464856290435791,63.278,85.021996,1.0004514820721684,450209.45535469055
> 55,1.7720111928349258,62.527977,82.96277,1.5965961740209864,1.5264092684173585,63.989998,85.29,1.0025294666387596,458399.58895516396
> 56,1.7685069872539325,62.57615,83.00268,1.5960595307173906,1.571856334915161,62.904,84.464,0.9913304107529777,466585.9665915966
> 57,1.7676819896856402,62.58264,83.00579,1.5965751370230874,1.519931905441284,64.072,85.214,0.9907919995638789,474773.672283411
> 58,1.7633828021756386,62.651028,83.05242,1.5966254869779268,1.5296032257843017,63.649998,85.182,1.0069580552529316,482964.8543624878
> 59,1.762230389919614,62.642574,83.03271,1.5966327063210837,1.518884241104126,64.066,85.411995,0.9922091547323733,491153.0843036175
> 60,1.7105733353304722,63.817917,83.7703,1.5964635649403849,1.4506889158630372,65.521996,86.222,0.9931325693519748,499341.74523472786
> 61,1.7047658753585624,63.9427,83.81546,1.5963242304551375,1.4501313687896729,65.46,86.214,0.9904440166998882,507529.5082395077
> 62,1.7029816968330318,63.94094,83.83007,1.5960700542895825,1.443698380355835,65.626,86.332,0.999058375553209,515716.308709383
> 63,1.7006617817973932,63.97508,83.89523,1.5957233719535164,1.4619855323791504,65.278,86.145996,1.0029854373056062,523903.1655244827
> 64,1.7011770515706328,63.989563,83.84739,1.5961855434394858,1.502848649597168,64.369995,85.502,0.9881741732967143,532088.5214724541
> 65,1.701400187242035,63.9714,83.86066,1.596170193093878,1.4573842282104492,65.383995,86.131996,0.9854576210586392,540273.5961740017
> 66,1.7005492970140317,64.00479,83.87039,1.5958774974891594,1.4698494776153563,64.906,86.058,0.9978820207167645,548459.2700073719
> 67,1.7005864492513805,63.93207,83.84804,1.6865760898971176,1.5263512521362306,63.904,85.259995,0.9936201913016183,557097.973174572
> 68,1.6998434647688,63.985138,83.89892,1.6153854569712363,1.45822073387146,65.27,86.133995,1.003535471400436,565382.2523198128
> 69,1.7003657271536816,63.96872,83.85166,1.5963282653263637,1.481093205871582,64.79,85.764,0.9857255354219553,573567.9607219696
> 70,1.7003885606694944,63.928326,83.8484,1.5965747860404518,1.505466459503174,64.074,85.436,1.0053336328389693,581758.9002225399
> 71,1.7015631769043245,63.9033,83.847626,1.595787447625464,1.5278383959960937,63.808,85.173996,0.9900182327445672,589942.877510786
> 72,1.697550265988844,63.966656,83.911835,1.5956486492366582,1.4644882872772216,65.159996,85.964,0.9959038544674309,598127.0380961895
> 73,1.700625746160773,63.914783,83.86695,1.5958980614131504,1.454816374053955,65.32,86.285995,1.0093149773928585,606314.997260809
> 74,1.7021390240779841,63.886078,83.840225,1.5969835279466627,1.5105508098602294,64.284,85.423996,0.9932024612718698,614505.14006567
> 75,1.7023710900860165,63.92633,83.85161,1.5959557027845355,1.4780098268127442,64.902,85.81,0.9847620798616993,622688.6121582985
> 76,1.6997852312980404,63.918262,83.88021,1.595850592059689,1.4782607787322999,64.902,85.818,1.0041363190631478,630875.3205928802
> 77,1.6992308229059185,64.01019,83.882286,1.596750420742816,1.4733256831359862,65.096,86.012,0.9946229615989997,639064.9259705544
> 78,1.7002029050045773,63.91405,83.83968,1.5969988569989428,1.5069794171905517,64.434,85.444,0.9870273081623778,647253.9411637783
> 79,1.7007536462828836,63.914997,83.83266,1.5961824518102747,1.5035199520874023,64.416,85.486,1.0089637515496235,655443.2620053291
> 80,1.6994928737155506,63.906315,83.87964,1.5960338774975482,1.464080915145874,65.254,86.076,1.0079378327544855,663631.658523798
> 81,1.6979317820993614,63.940815,83.897095,1.5959332480416313,1.4795377980804443,64.708,85.796,0.9878113135999563,671816.1759848595
> 82,1.7000740477349692,63.89565,83.85333,1.596167873312067,1.4589048153686524,65.318,86.06,0.9980773633840133,680003.7541818619
> 83,1.6971413652078178,64.00678,83.871376,1.5966329814670803,1.5329412049865723,63.573997,84.992,0.98514666727611,688190.5998697281
> 84,1.6984173363687638,63.93113,83.899086,1.5961399444214233,1.4762832211303711,64.944,85.974,0.9895148849000737,696375.9652450085
> 85,1.6983990221635619,63.95159,83.88598,1.5962878441596247,1.4815700963592529,64.892,85.908,0.9939260884207122,704562.8491721153
> 86,1.69557271798417,64.01502,83.90125,1.5967913878666653,1.516679326171875,64.236,85.341995,1.0039535797372157,712754.3144705296
> 87,1.6994829859870804,63.966194,83.8501,1.5966947032974197,1.4664484536743163,64.972,86.077995,1.0077411155311429,720945.9214494228
> 88,1.6970900383199357,63.905487,83.8847,1.5965777459559025,1.5180966523742676,63.934,85.368,1.0067482432540582,729136.6450090408
> 89,1.6975512266464625,63.927776,83.87759,1.5965711550755457,1.465786263961792,65.28,85.979996,0.9965298406931818,737325.5609092712
> ```

Thanks for your guide. We used lr=0.01 but optimizer = SGD as default. We reset optimizer to radam and train it now.

**Comment by mostafaelhoushi** [comment]
Hi @PoonKinWang 
Can you please tell me how is the training going?

Thanks

**Comment by PoonKinWang** [comment]
> Hi @PoonKinWang
> Can you please tell me how is the training going?
> 
> Thanks

We have achieved your reported accuracy after 90 epochs. 
Some studies we are doing are based on DeepShift. 
Thanks for your excellent work!

**Comment by mostafaelhoushi** [comment]
I am glad to hear that! I will close the issue but please don't hesitate to re-open it or create another issue if any problem or discrepancy from the paper's results arises.
